/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import BaseDatos.CiberDB;

/**
 *
 * @author Robert
 */
public class Ciber extends javax.swing.JFrame {

    public static Ciber main;
    
    private CiberDB data;
    private DefaultTableModel modeloRegistros = new DefaultTableModel(
            new Object[]{ "Nombre", "Marca" }, 0);
    public DefaultTableModel modeloTiempo = new DefaultTableModel(
            new Object[]{ "Computadora", "Hora Inicio", "Transcurriendo", "Hora Finaliza" }, 0);
    private DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    
    /**
     * Creates new form Ventana
     */
    public Ciber(CiberDB data) {
        initComponents();
        main = this;
        this.data = data;
        setLocationRelativeTo(null);
        tablaRegistros.setModel(modeloRegistros);
        tablaTiempos.setModel(modeloTiempo);
        comboMaquinas.setModel(modeloCombo);
    }

    private void actualizarTablaRegistros()
    {
        //Se actualiza toda (supongo que se llama al inciar el programa :v)
    }
    
    private void actualizarTablaRegistros(CiberDB.Maquina nuevo)
    {
        //Se actualiza solo al agregar un registro
        modeloRegistros.addRow(new Object[]{ nuevo.getName(), nuevo.getBrand() });
        modeloCombo.addElement(nuevo.getName());
    }
    
    public void actualizarTiempoTabla(int fila, String tiempo)
    {
        modeloTiempo.setValueAt(tiempo, fila, 2);
    }
    
    private void limpiarCamposRegistro()
    {
        nombreText.setText("");
        marcaText.setText("");
    }
    
    private void limpiarCamposTiempo()
    {
        horasText.setText("");
        minutosText.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Manejo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CamposBoton1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboMaquinas = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        libre = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        horasText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        minutosText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        iniciarTiempo = new javax.swing.JButton();
        ScrollTabla1 = new javax.swing.JScrollPane();
        tablaTiempos = new javax.swing.JTable();
        Registro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CamposBoton = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        registrar = new javax.swing.JButton();
        ScrollTabla = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Nombre.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("CIBER LYN");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMINISTRAR TIEMPOS");

        jPanel4.setPreferredSize(new java.awt.Dimension(750, 44));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Maquiná");
        jPanel4.add(jLabel5);

        comboMaquinas.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel4.add(comboMaquinas);

        jPanel5.setPreferredSize(new java.awt.Dimension(750, 44));

        libre.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        libre.setText("Libre");
        libre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libreActionPerformed(evt);
            }
        });
        jPanel5.add(libre);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 20));
        jPanel5.add(jSeparator1);

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Horas");
        jPanel5.add(jLabel6);

        horasText.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        horasText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horasText.setPreferredSize(new java.awt.Dimension(30, 22));
        horasText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasTextActionPerformed(evt);
            }
        });
        jPanel5.add(horasText);

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Minutos");
        jPanel5.add(jLabel7);

        minutosText.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        minutosText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minutosText.setPreferredSize(new java.awt.Dimension(30, 22));
        minutosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutosTextActionPerformed(evt);
            }
        });
        jPanel5.add(minutosText);

        iniciarTiempo.setText("Empezar tiempo");
        iniciarTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarTiempoActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarTiempo);

        javax.swing.GroupLayout CamposBoton1Layout = new javax.swing.GroupLayout(CamposBoton1);
        CamposBoton1.setLayout(CamposBoton1Layout);
        CamposBoton1Layout.setHorizontalGroup(
            CamposBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamposBoton1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(321, 321, 321))
            .addGroup(CamposBoton1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(CamposBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        CamposBoton1Layout.setVerticalGroup(
            CamposBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamposBoton1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tablaTiempos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computadora", "Hora Inicio", "Transcurriendo", "Hora Finaliza"
            }
        ));
        ScrollTabla1.setViewportView(tablaTiempos);
        if (tablaTiempos.getColumnModel().getColumnCount() > 0) {
            tablaTiempos.getColumnModel().getColumn(0).setResizable(false);
            tablaTiempos.getColumnModel().getColumn(1).setResizable(false);
            tablaTiempos.getColumnModel().getColumn(2).setResizable(false);
            tablaTiempos.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout ManejoLayout = new javax.swing.GroupLayout(Manejo);
        Manejo.setLayout(ManejoLayout);
        ManejoLayout.setHorizontalGroup(
            ManejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManejoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollTabla1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CamposBoton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ManejoLayout.setVerticalGroup(
            ManejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManejoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CamposBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollTabla1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Administrar tiempos", Manejo);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR COMPUTADORA");

        jPanel2.setPreferredSize(new java.awt.Dimension(750, 44));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre máquina");
        jPanel2.add(jLabel2);

        nombreText.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        nombreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreText.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel2.add(nombreText);

        jPanel3.setPreferredSize(new java.awt.Dimension(750, 44));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Marca");
        jLabel3.setPreferredSize(new java.awt.Dimension(112, 20));
        jPanel3.add(jLabel3);

        marcaText.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        marcaText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marcaText.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(marcaText);

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel6.add(registrar);

        javax.swing.GroupLayout CamposBotonLayout = new javax.swing.GroupLayout(CamposBoton);
        CamposBoton.setLayout(CamposBotonLayout);
        CamposBotonLayout.setHorizontalGroup(
            CamposBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamposBotonLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(CamposBotonLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(CamposBotonLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(332, 332, 332))
        );
        CamposBotonLayout.setVerticalGroup(
            CamposBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CamposBotonLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca"
            }
        ));
        ScrollTabla.setViewportView(tablaRegistros);
        if (tablaRegistros.getColumnModel().getColumnCount() > 0) {
            tablaRegistros.getColumnModel().getColumn(0).setResizable(false);
            tablaRegistros.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro);
        Registro.setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollTabla)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CamposBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CamposBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar Máquina", Registro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        if(nombreText.getText().isEmpty() || marcaText.getText().isEmpty())
            return;
        data.registrarMaquina(nombreText.getText(), marcaText.getText());
        actualizarTablaRegistros(data.ultimoRegistro());
        limpiarCamposRegistro();
    }//GEN-LAST:event_registrarActionPerformed

    private void iniciarTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarTiempoActionPerformed
        // TODO add your handling code here:
        GregorianCalendar c = new GregorianCalendar();
        String inicio = c.get(Calendar.HOUR_OF_DAY) + ":" + c.get(Calendar.MINUTE) + ":"+ c.get(Calendar.SECOND);
        try{c.add(Calendar.HOUR_OF_DAY, Integer.parseInt(horasText.getText()));}catch(Exception ex){}
        try{c.add(Calendar.MINUTE, Integer.parseInt(minutosText.getText()));}catch(Exception ex){}
        String fin = c.get(Calendar.HOUR_OF_DAY) + ":" + c.get(Calendar.MINUTE) + ":"+ c.get(Calendar.SECOND);
        modeloTiempo.addRow(new Object[]{ modeloCombo.getSelectedItem(), inicio, "", libre.isSelected() ? "Libre" : fin });
        data.IniciarConteo(modeloCombo.getSelectedItem().toString(), modeloTiempo.getRowCount() - 1,
                Calendar.getInstance(), c, libre.isSelected());
        limpiarCamposTiempo();
    }//GEN-LAST:event_iniciarTiempoActionPerformed

    private void libreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libreActionPerformed
        // TODO add your handling code here:
        horasText.setEnabled(!libre.isSelected());
        minutosText.setEnabled(!libre.isSelected());
    }//GEN-LAST:event_libreActionPerformed

    private void minutosTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutosTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutosTextActionPerformed

    private void horasTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasTextActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ventana().setVisible(true);
//            }
//        });
//        //new Ventana().setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CamposBoton;
    private javax.swing.JPanel CamposBoton1;
    private javax.swing.JPanel Manejo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Registro;
    private javax.swing.JScrollPane ScrollTabla;
    private javax.swing.JScrollPane ScrollTabla1;
    private javax.swing.JComboBox<String> comboMaquinas;
    private javax.swing.JTextField horasText;
    private javax.swing.JButton iniciarTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox libre;
    private javax.swing.JTextField marcaText;
    private javax.swing.JTextField minutosText;
    private javax.swing.JTextField nombreText;
    private javax.swing.JButton registrar;
    private javax.swing.JTable tablaRegistros;
    public javax.swing.JTable tablaTiempos;
    // End of variables declaration//GEN-END:variables
}
