/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Animaciones.Animacion;
import Animaciones.Controlador;
import java.awt.Color;
import java.awt.Component;
import java.util.concurrent.Callable;
import javax.swing.ImageIcon;

/**
 *
 * @author Robert
 */
public class Confirmacion extends javax.swing.JFrame {
    
    Component c;
    
    Animacion show, hide;
    
    Callable<Void> accion;
    /**
     * Creates new form Salida
     */
//    public Salida() {
//        initComponents();
//        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/papeleria.png")).getImage());
//        //setLocationRelativeTo(c);
//        setOpacity(0);
//    }
    
    public Confirmacion(Component c) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/papeleria.png")).getImage());
        setLocationRelativeTo(c);
        show = new Animacion(this, getX(), getY(), getWidth(), getHeight(), null, 3);
        show.setUpdateAction(() -> Opacidad(show.getLerp(), false));
        hide = new Animacion(this, getX(), getY(), getWidth(), getHeight(), () -> { setOpacity(0); return null; }, 3);
        hide.setUpdateAction(() -> Opacidad(hide.getLerp(), true));
        //setOpacity(0);
        this.c = c;
        setOpacity(0);
        setVisible(true);
        //hide.Iniciar();
    }
    
    public void setAccion(Callable<Void> accion){ this.accion = accion; }

    public void Mostrar(String pregunta, Callable<Void> accion)
    {
        this.accion = accion;
        preguntaa.setText(pregunta);
        setLocationRelativeTo(c);
        requestFocus();
        //Login.ins.Darken();
        //preguntaa.setText(pregunta);
        c.setEnabled(false);
        //Controlador.main.AccionesVentana(this, () -> { setOpacity(1);setVisible(true); return null;}, 6);
        //setVisible(true);
        show.Reinciar();
    }
    public void Ocultar(boolean todo)
    {
        if(todo)
            try { accion.call(); } catch(Exception ex){}
        c.setEnabled(true);
        //setVisible(false);
        hide.Iniciar();
    }
    
    
    public Void Opacidad(float lerp, boolean min)
    {
        if(min)
            setOpacity(1 - lerp);
        else
            setOpacity(lerp);
        System.out.println("dsads");
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        preguntaa = new javax.swing.JLabel();
        botones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(387, 151));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(387, 151));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        preguntaa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        preguntaa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preguntaa.setText("Pregunta");
        preguntaa.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(preguntaa);

        botones.setBackground(new java.awt.Color(255, 255, 255));
        botones.setPreferredSize(new java.awt.Dimension(300, 50));
        botones.setRequestFocusEnabled(false);

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SI");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        botones.add(jButton1);

        jSeparator1.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(20, 10));
        botones.add(jSeparator1);

        jButton2.setBackground(new java.awt.Color(255, 102, 51));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NO");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        botones.add(jButton2);

        jPanel1.add(botones);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 387, 151));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //SI
        Ocultar(true);
        //Login.ins.CerrarDef();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Ocultar(false);
    }//GEN-LAST:event_jButton2ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Salida().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel preguntaa;
    // End of variables declaration//GEN-END:variables
}
