/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Animacion.Animacion;
import Animacion.Fade;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author omara
 */
public class MensajeContinuar extends javax.swing.JFrame {

   
    Dimension screenSize;
    int xCenter, yCenter;
   public  boolean continar;
    public MensajeContinuar( ) {
        initComponents();
        
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        xCenter = (screenSize.width - this.getWidth())/2;
        yCenter = 0;
        this.setLocation(xCenter, yCenter);
        animacion();
    }

    public void animacion() {
        
       
          if ((this.getY() + (this.getHeight())) > screenSize.height) {
            
        } else {
            Animacion.bajar(this.getY(), (this.getY() + (this.getHeight() / 2)), 1, 2, this);
//            Animacion.subir(this.getY(), (this.getY()-(this.getHeight()/2)), 2, 5, this);
        }  
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensaje = new javax.swing.JTextPane();
        BtnRegistro1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistro.setBackground(new java.awt.Color(255, 102, 0));
        BtnRegistro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistro.setText("Continuar");
        BtnRegistro.setBorder(null);
        BtnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistro.setFocusable(false);
        BtnRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnRegistroMouseMoved(evt);
            }
        });
        BtnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRegistroMouseExited(evt);
            }
        });
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, 50));

        Mensaje.setEditable(false);
        Mensaje.setBorder(null);
        Mensaje.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jScrollPane1.setViewportView(Mensaje);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 190));

        BtnRegistro1.setBackground(new java.awt.Color(255, 0, 0));
        BtnRegistro1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistro1.setText("Cancelar");
        BtnRegistro1.setBorder(null);
        BtnRegistro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistro1.setFocusable(false);
        BtnRegistro1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnRegistro1MouseMoved(evt);
            }
        });
        BtnRegistro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRegistro1MouseExited(evt);
            }
        });
        BtnRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistro1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, 50));

        jPanel2.setBackground(new java.awt.Color(238, 112, 82));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Advertencia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        // TODO add your handling code here:
        continar=true;
          Fade.JFrameFadeOut(1f, 0f, 0.1f, 30, this,Fade.DISPOSE);
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void BtnRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistroMouseExited
        // TODO add your handling code here:
        BtnRegistro.setBackground(new java.awt.Color(255, 102, 0));
    }//GEN-LAST:event_BtnRegistroMouseExited

    private void BtnRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistroMouseMoved
        // TODO add your handling code here:
        //[255,122,47]
        
        BtnRegistro.setBackground(new java.awt.Color(255, 122, 47));
    }//GEN-LAST:event_BtnRegistroMouseMoved

    private void BtnRegistro1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistro1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistro1MouseMoved

    private void BtnRegistro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistro1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistro1MouseExited

    private void BtnRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistro1ActionPerformed
        // TODO add your handling code here:
        Fade.JFrameFadeOut(1f, 0f, 0.1f, 30, this,Fade.DISPOSE);
        continar=false;
    }//GEN-LAST:event_BtnRegistro1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton BtnRegistro1;
    public static javax.swing.JTextPane Mensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
